name: Hello World!

on:
    push:
        branches:
            - main

jobs:
    hello_world_job:
        runs-on: ubuntu-22.04
        steps:
            - name: Say hello
              run: |
                echo "Hello World!"
                echo "date:" 
                date --date='@2147483647'
                echo "list directory:"
                ls -la
