name: Deployment pipeline

on:
    push:
        branches:
            - main

jobs:
    simple_deployment_pipeline:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'
            - name: Install dependencies
              run: npm install
            - name: Check style
              run: npm run eslint
            - name: Make a build
              run: npm run build
            - name: Test the app
              run: npm run test
            - name: Update playwright browsers
              run: npx playwright install
            - name: Playwright the app
              run: npm run test:e2e
              
